allowTools:
  WOODEN_SHOVEL:
    - DIRT
    - GRASS
    - SAND
    - GRAVEL
  STONE_SHOVEL:
    - DIRT
    - GRASS
    - SAND
    - GRAVEL
  WOODEN_PICKAXE:
    - STONE
    - GRANITE
    - DIORITE
    - ANDESITE
  STONE_PICKAXE:
    - STONE
    - GRANITE
    - DIORITE
    - ANDESITE
radius: 2
near: 0
far: 3
consume: true
forceOnSneaking: false
dontDigFloor: true
switchFromPunch: false
switchRightClick: true