allowTools:
  WOOD_SPADE:
    - DIRT
    - GRASS
    - SAND
  WOOD_PICKAXE:
    - STONE
radius: 2
near: 0
far: 3
consume: true
forceOnSneaking: false
dontDigFloor: true
switchFromPunch: false
switchRightClick: true